In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sys
import os

In [5]:
sys.path.append(os.path.abspath("../src"))

from preprocessing import Preprocessing

In [6]:
df = pd.read_csv("../data/raw/ev_market_2026.csv")

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  2000 non-null   str
 1   model                  2000 non-null   str
 2   year                   2000 non-null   int64
 3   variant                2000 non-null   str
 4   price_usd              2000 non-null   float64
 5   battery_capacity_kwh   2000 non-null   float64
 6   range_miles            2000 non-null   float64
 7   charging_speed_kw      2000 non-null   float64
 8   acceleration_0_60_mph  2000 non-null   float64
 9   top_speed_mph          2000 non-null   float64
 10  horsepower             2000 non-null   float64
 11  torque_nm              2000 non-null   float64
 12  drive_type             2000 non-null   str
 13  seating_capacity       2000 non-null   int64
 14  body_type              2000 non-null   str
 15  cargo_volume_cubic_ft  2000 non-null   float64
 16  weight_kg              2000 non-null   float64
 17  safety_rating          2000 non-null   int64
 18  autopilot_level        2000 non-null   int64
 19  country_of_origin      2000 non-null   str
 20  market_segment         2000 non-null   str
 21  annual_sales_units     2000 non-null   int64
 22  customer_rating        2000 non-null   float64
 23  warranty_years         2000 non-null   int64
dtypes: float64(11), int64(6), str(7)
memory usage: 375.1 KB

In [9]:
preprocessor = Preprocessing(df)

preprocessed_df = (
    preprocessor
    .handling_missing_values()
    .encoding(target_col="price_usd")
    .scaling(target_col="price_usd")
    .get_df()
)

In [10]:
preprocessed_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   brand                  2000 non-null   str
 1   model                  2000 non-null   str
 2   year                   2000 non-null   float64
 3   variant                2000 non-null   str
 4   price_usd              2000 non-null   float64
 5   battery_capacity_kwh   2000 non-null   float64
 6   range_miles            2000 non-null   float64
 7   charging_speed_kw      2000 non-null   float64
 8   acceleration_0_60_mph  2000 non-null   float64
 9   top_speed_mph          2000 non-null   float64
 10  horsepower             2000 non-null   float64
 11  torque_nm              2000 non-null   float64
 12  drive_type             2000 non-null   str
 13  seating_capacity       2000 non-null   float64
 14  body_type              2000 non-null   str
 15  cargo_volume_cubic_ft  2000 non-null   float64
 16  weight_kg              2000 non-null   float64
 17  safety_rating          2000 non-null   float64
 18  autopilot_level        2000 non-null   float64
 19  country_of_origin      2000 non-null   str
 20  market_segment         2000 non-null   str
 21  annual_sales_units     2000 non-null   float64
 22  customer_rating        2000 non-null   float64
 23  warranty_years         2000 non-null   float64
dtypes: float64(17), str(7)
memory usage: 375.1 KB

In [12]:
preprocessed_df.sample(10)

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
478,Fisker,Ocean,0.688905,Premium,141027.00,-1.024153,-1.011477,-0.694230,0.521643,0.149956,...,Sedan,-0.705751,-0.678082,0.942565,-0.135438,US,Luxury,-1.120870,-0.710409,-0.475172
1023,Fisker,Ronin,-0.020210,Performance,77587.25,0.181155,0.481260,0.345763,-1.390338,1.593927,...,Sedan,-0.589855,-0.508669,-0.570381,-0.135438,US,Premium,-0.995772,-0.414475,0.345505
1082,Volkswagen,ID. Aero,0.688905,Premium,112803.13,0.325592,0.495342,-1.298217,0.295874,-0.331367,...,Truck,1.697840,2.011681,-0.570381,-0.135438,Germany,Luxury,0.904724,0.695280,-1.295848
1924,Ford,F-150 Lightning,0.688905,Performance,55789.82,1.416346,1.312123,0.034506,-2.173474,1.690192,...,Truck,0.589265,1.584238,-2.083326,-1.223295,US,Mid-range,-0.671097,1.583083,-0.475172
1235,Volkswagen,ID. Aero,-0.020210,Performance,115397.77,0.245903,0.284106,0.422342,-1.975927,1.690192,...,Sedan,-0.604972,-0.977813,-0.570381,-1.223295,Germany,Luxury,1.578652,-0.229516,-0.475172
298,BMW,i4,0.688905,Base,85729.44,-0.735278,-0.997395,-0.117417,0.253542,0.149956,...,Truck,1.118358,2.089871,0.942565,0.952419,Germany,Premium,-0.948622,-0.340491,1.166181
285,Tesla,Model S,-1.438440,Premium,59089.35,0.101465,0.086952,1.106613,0.902628,-0.572029,...,Sedan,-0.473959,-1.006483,0.942565,0.952419,US,Mid-range,0.009961,0.251378,0.345505
1693,Tesla,Model X,-0.729325,Performance,111766.84,1.505997,1.396618,1.762476,-1.637273,1.690192,...,Hatchback,-1.083675,-0.292341,-0.570381,0.952419,US,Luxury,0.446326,1.768042,0.345505
534,Ford,Mustang Mach-E,-0.729325,Base,67976.38,-1.278164,-1.166384,-0.584302,0.077160,0.053692,...,SUV,-0.322789,1.083817,-0.570381,-1.223295,US,Premium,-1.026836,-1.117319,-1.295848
130,Volkswagen,ID. Buzz,0.688905,Standard,60229.21,-1.696536,-1.574775,-0.214993,1.572880,-0.957088,...,SUV,-0.010373,0.974350,0.942565,-0.135438,Germany,Mid-range,0.812524,-1.376262,-0.475172

In [17]:
encoder = Preprocessing(preprocessed_df)

encoded_df = encoder.encoding(target_col="price_usd").get_df()

In [18]:
encoded_df.head()

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,Volkswagen,ID. Buzz,-0.729325,Performance,104880.80,2.193322,1.945833,0.979393,-1.827766,1.449530,...,Truck,0.407862,0.335792,-0.570381,0.952419,Germany,Luxury,0.685856,1.583083,-0.475172
1,Toyota,bZ Compact SUV,-1.438440,Premium,48217.41,-0.790064,-0.603087,-0.087773,0.098326,-0.283235,...,SUV,1.153631,-0.461754,-0.570381,-1.223295,Japan,Mid-range,-1.158478,-0.044557,-1.295848
2,GM/Chevrolet,Bolt EV,-0.020210,Premium,49651.12,-0.819948,-0.518592,-0.621357,0.853241,-0.812691,...,Van,1.556749,-0.920474,-0.570381,-0.135438,US,Mid-range,-1.069172,0.473329,-1.295848
3,Kia,Sportage EV,-0.020210,Long Range,38131.56,1.386463,1.227629,-1.095653,-0.684810,0.535015,...,SUV,0.992384,0.127283,-0.570381,0.952419,South Korea,Mid-range,-0.023193,0.880239,-1.295848
4,Tesla,Model 3,-1.438440,Long Range,144079.87,0.958130,0.734744,1.769887,0.006607,0.005559,...,SUV,-0.393335,0.893553,-0.570381,0.952419,US,Luxury,0.631189,0.954222,-0.475172

In [19]:
# manual encoding

from sklearn.preprocessing import LabelEncoder

label_encoders = {}
categorical_cols = encoded_df.select_dtypes(include="object").columns
for col in categorical_cols:
    le = LabelEncoder()
    encoded_df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

C:\Users\mrcoo\AppData\Local\Temp\ipykernel_22484\1976881707.py:6: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = encoded_df.select_dtypes(include="object").columns

In [20]:
encoded_df.head(5)

,brand,model,year,variant,price_usd,battery_capacity_kwh,range_miles,charging_speed_kw,acceleration_0_60_mph,top_speed_mph,...,body_type,cargo_volume_cubic_ft,weight_kg,safety_rating,autopilot_level,country_of_origin,market_segment,annual_sales_units,customer_rating,warranty_years
0,17,29,-0.729325,2,104880.80,2.193322,1.945833,0.979393,-1.827766,1.449530,...,4,0.407862,0.335792,-0.570381,0.952419,1,1,0.685856,1.583083,-0.475172
1,16,64,-1.438440,3,48217.41,-0.790064,-0.603087,-0.087773,0.098326,-0.283235,...,2,1.153631,-0.461754,-0.570381,-1.223295,2,2,-1.158478,-0.044557,-1.295848
2,5,7,-0.020210,3,49651.12,-0.819948,-0.518592,-0.621357,0.853241,-0.812691,...,5,1.556749,-0.920474,-0.570381,-0.135438,5,2,-1.069172,0.473329,-1.295848
3,8,59,-0.020210,1,38131.56,1.386463,1.227629,-1.095653,-0.684810,0.535015,...,2,0.992384,0.127283,-0.570381,0.952419,3,2,-0.023193,0.880239,-1.295848
4,15,40,-1.438440,1,144079.87,0.958130,0.734744,1.769887,0.006607,0.005559,...,2,-0.393335,0.893553,-0.570381,0.952419,5,1,0.631189,0.954222,-0.475172

In [22]:
# saving preprocessed model


import os

def save_dataframe(df, folder, filename):
    os.makedirs(folder, exist_ok=True)
    path = os.path.join(folder, filename)
    df.to_csv(path, index=False)
    print(f"Saved to: {path}")



save_dataframe(encoded_df, "../data/preprocessed", "encoded_df.csv")

Saved to: ../data/preprocessed\encoded_df.csv